@MailService_HostAddress = http://localhost:5252

POST {{MailService_HostAddress}}/confirmregistration/
Accept: application/json

###

GET {{MailService_HostAddress}}/restoreaccess/
Accept: application/json

###
