
version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD='YOUR PASSWORD'
    ports:
      - "1433:1433"
    volumes:
        #${HOME} - absolute path to your home directory
        #database data should be stored in the /var/opt/mssql directory
        #but you can access this data using your host ${HOME}/docker-containers/mssql/data
      - ${HOME}/docker-containers/mssql/data:/var/opt/mssql
volumes:
  mssql-data:

